export default{
	state:{
		list:[
			{
				name:"王一",
				tel:"18511773322",
				city:"北京市海淀区",
				detail:"3号楼",
				isDefault:false
			},
			{
				name:"王二",
				tel:"18511773311",
				city:"北京市朝阳区",
				detail:"1号楼",
				isDefault:true
			},
		]
	},
	getters:{
		
	},
	mutations:{
		createAddress(state,obj){
			state.list.unshift(obj);
		},
		updateAddress(state,{index,item}){
			for(let key in item){
				state.list[index][key]=item[key];
			}
		},
		//把之前选中的改为未选中
		removeAddress(state){
			state.list.forEach(v=>{
				if(v.isDefault){
					v.isDefault=false;
				}
			})
		}
	},
	actions:{
		createAddressFn({commit},obj){
			if(obj.isDefault){
				commit("removeAddress");
			}
			commit('createAddress',obj)
		},
		updateAddressFn({commit},obj){
			if(obj.item.isDefault){
				commit("removeAddress");
			}
			commit('updateAddress',obj);
		}
	}
}